name: zxbase_flutter_ui
description: Shared UI components.
version: 1.7.1
homepage: https://zxbase.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_avatar: ^1.0.0
  intl: ^0.18.0
  timeago: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0

flutter:
  assets:
    - assets/images/
