name: Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deps:
    name: Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Check flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Check outdated dependencies
        run: ./tool/dependencies
